from __future__ import annotations

import csv
import hashlib
import os
from collections import Counter
from decimal import Decimal
from pathlib import Path

from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils.text import slugify

from dcim.models import PowerPort, Rack, Site
from netbox_power_plant.choices import (
    DesignStateChoices,
    InternalPowerBusAttachmentRoleChoices,
    InternalPowerBusRoleChoices,
    NodeKindChoices,
    PhaseModeChoices,
    PowerDomainKindChoices,
    PowerSystemScopeChoices,
    RedundancyTopologyChoices,
    SegmentKindChoices,
    SupplyTypeChoices,
    TerminalDirectionChoices,
    TerminalRoleChoices,
    TopologyStateChoices,
)
from netbox_power_plant.models import (
    ElectricalNode,
    ElectricalSegment,
    ElectricalTerminal,
    InternalPowerBus,
    InternalPowerBusAttachment,
    PowerHandoffPoint,
    PowerDomain,
    PowerSystem,
    RedundancyGroup,
)


MAD_SITE_SLUG = os.environ.get('MADISON_SITE_SLUG', 'mad-1')
POWER_SYSTEM_NAME = os.environ.get('MADISON_POWER_SYSTEM_NAME', 'MAD-1 Electrical Plant')
SOURCE_DIR = Path(os.environ.get('MADISON_ELECTRICAL_SOURCE_DIR', '/tmp/madison-electrical'))
CABINET_CIRCUIT_CSV = SOURCE_DIR / 'enovum_mad1_cabinet_circuit_schedule.csv'
SOURCE_MARKER = 'madison-power-plant-initial-pass'

LETTERS = tuple('ABCDEFGH')
DOMAIN_COLORS = {
    'A': 'e6194b',
    'B': '3cb44b',
    'C': 'ffe119',
    'D': '4363d8',
    'E': 'f58231',
    'F': '911eb4',
    'G': '46f0f0',
    'H': 'f032e6',
}

PRSG_FEEDER_BY_SYSTEM = {
    '1A': 'PRSG-1-1',
    '1B': 'PRSG-1-1',
    '1C': 'PRSG-1-2',
    '1D': 'PRSG-1-2',
    '1E': 'PRSG-1-3',
    '1F': 'PRSG-1-3',
    '1G': 'PRSG-1-4',
    '1H': 'PRSG-1-4',
    '2A': 'PRSG-2-1',
    '2B': 'PRSG-2-1',
    '2C': 'PRSG-2-2',
    '2D': 'PRSG-2-2',
    '2E': 'PRSG-2-3',
    '2F': 'PRSG-2-3',
    '2G': 'PRSG-2-4',
    '2H': 'PRSG-2-4',
    '3A': 'PRSG-1-1',
    '3B': 'PRSG-1-1',
    '3C': 'PRSG-2-2',
    '3D': 'PRSG-2-2',
    '3E': 'PRSG-2-3',
    '3F': 'PRSG-2-3',
    '3G': 'PRSG-1-4',
    '3H': 'PRSG-1-4',
}

NVL72_RACK_ROLE_SLUG = 'nvl72_poweredgexe9712'
POWER_SHELF_DEVICE_TYPE_SLUGS = ('gb300ps', 'ps33-33kw-power-shelf')
POWER_SHELF_PORT_NAME = 'busbar-output-1'
LOAD_DEVICE_TYPE_SLUGS = (
    'gb300ct',
    'poweredge-xe9712-gb300-compute-tray',
    'gb300st',
    'gb300-nvl72-nvlink-switch-tray',
    'sn2201_m',
)
LOAD_POWER_PORT_NAMES = ('nvl72-busbar', 'busbar-input-1')


def stable_slug(*parts, max_length=100):
    raw = '-'.join(str(part) for part in parts if part is not None)
    base = slugify(raw) or 'object'
    digest = hashlib.sha1(raw.encode()).hexdigest()[:8]
    suffix = f'-{digest}'
    return f'{base[: max_length - len(suffix)]}{suffix}'


def short_description(text):
    return text[:200]


def unique_display_name(*parts, max_length=100):
    raw = ' '.join(str(part) for part in parts if part is not None)
    if len(raw) <= max_length:
        return raw
    digest = hashlib.sha1(raw.encode()).hexdigest()[:8]
    return f'{raw[: max_length - 9]}-{digest}'


def q2(value):
    return Decimal(str(value)).quantize(Decimal('0.01'))


def save_changed(obj, desired, counters, key):
    changed = False
    for field, value in desired.items():
        if getattr(obj, field) != value:
            setattr(obj, field, value)
            changed = True
    if changed:
        obj.full_clean()
        obj.save()
    counters[f'{key}_updated' if changed else f'{key}_unchanged'] += 1
    return obj


def upsert_power_system(site, counters):
    slug = stable_slug('power-system', POWER_SYSTEM_NAME)
    obj, created = PowerSystem.objects.get_or_create(
        slug=slug,
        defaults={
            'name': POWER_SYSTEM_NAME,
            'site': site,
        },
    )
    desired = {
        'name': POWER_SYSTEM_NAME,
        'site': site,
        'scope_type': PowerSystemScopeChoices.SCOPE_BUILDING,
        'upstream_supply_type': SupplyTypeChoices.SUPPLY_MIXED,
        'nominal_distribution_voltage': None,
        'frequency_hz': Decimal('60.00'),
        'is_template_derived': False,
        'design_state': DesignStateChoices.STATE_PLANNED,
        'description': 'Drawing-derived MAD-1 power plant model; generated by local-dev initial pass.',
    }
    counters['power_system_created' if created else 'power_system_seen'] += 1
    return save_changed(obj, desired, counters, 'power_system')


def upsert_domain(power_system, code, name, kind, priority, counters):
    obj, created = PowerDomain.objects.get_or_create(
        power_system=power_system,
        code=code,
        defaults={
            'slug': stable_slug('power-domain', code),
            'name': name,
        },
    )
    letter = code[-1] if code and code[-1] in DOMAIN_COLORS else None
    desired = {
        'name': name,
        'slug': stable_slug('power-domain', code),
        'power_system': power_system,
        'code': code,
        'kind': kind,
        'color': DOMAIN_COLORS.get(letter, ''),
        'priority': priority,
        'failure_isolation_depth': 3,
        'description': short_description(f'{SOURCE_MARKER}; drawing-derived electrical domain {code}.'),
    }
    counters['power_domain_created' if created else 'power_domain_seen'] += 1
    return save_changed(obj, desired, counters, 'power_domain')


def upsert_redundancy_group(power_system, domains, counters):
    slug = stable_slug('redundancy-group', 'mad-1-it-a-through-h')
    obj, created = RedundancyGroup.objects.get_or_create(
        slug=slug,
        defaults={
            'name': 'MAD-1 IT A-H distributed source set',
            'power_system': power_system,
        },
    )
    desired = {
        'name': 'MAD-1 IT A-H distributed source set',
        'slug': slug,
        'power_system': power_system,
        'topology_type': RedundancyTopologyChoices.TOPOLOGY_DISTRIBUTED,
        'min_distinct_paths': 2,
        'requires_domain_isolation': True,
        'notes_on_failover': 'Initial drawing-derived contract for rack delivery checks across source systems A-H.',
        'description': short_description(f'{SOURCE_MARKER}; preliminary redundancy group for IT cabinet feeds.'),
    }
    counters['redundancy_group_created' if created else 'redundancy_group_seen'] += 1
    save_changed(obj, desired, counters, 'redundancy_group')
    obj.power_domains.set(domains)
    return obj


def upsert_node(power_system, site, *, name, kind, role='', parent=None, model='', manufacturer='', input_v=None, output_v=None, capacity_kw=None, counters):
    slug = stable_slug('node', name)
    obj, created = ElectricalNode.objects.get_or_create(
        slug=slug,
        defaults={
            'name': name,
            'power_system': power_system,
            'site': site,
        },
    )
    phase_mode = PhaseModeChoices.MODE_THREE_PHASE
    desired = {
        'name': name,
        'slug': slug,
        'power_system': power_system,
        'site': site,
        'parent_node': parent,
        'node_kind': kind,
        'equipment_role': role,
        'manufacturer': manufacturer,
        'model': model,
        'install_state': TopologyStateChoices.STATE_PLANNED,
        'topology_state': TopologyStateChoices.STATE_PLANNED,
        'rated_input_voltage_min': Decimal(str(input_v)) if input_v is not None else None,
        'rated_input_voltage_max': Decimal(str(input_v)) if input_v is not None else None,
        'rated_output_voltage_min': Decimal(str(output_v)) if output_v is not None else None,
        'rated_output_voltage_max': Decimal(str(output_v)) if output_v is not None else None,
        'frequency_hz': Decimal('60.00'),
        'phase_mode': phase_mode,
        'pole_count': 3,
        'installed_capacity_kw': q2(capacity_kw) if capacity_kw is not None else None,
        'usable_capacity_kw': q2(capacity_kw) if capacity_kw is not None else None,
        'description': short_description(f'{SOURCE_MARKER}; source: ENOVUM MAD-1 electrical drawings.'),
    }
    counters['electrical_node_created' if created else 'electrical_node_seen'] += 1
    return save_changed(obj, desired, counters, 'electrical_node')


def upsert_terminal(node, *, name, role, direction, voltage=None, amperage=None, connector='', index=None, counters):
    display_name = unique_display_name(node.name, name)
    slug = stable_slug('terminal', node.name, name)
    obj, created = ElectricalTerminal.objects.get_or_create(
        slug=slug,
        defaults={
            'name': display_name,
            'node': node,
        },
    )
    desired = {
        'name': display_name,
        'slug': slug,
        'node': node,
        'terminal_role': role,
        'direction': direction,
        'supply_type': SupplyTypeChoices.SUPPLY_AC,
        'voltage_nominal': Decimal(str(voltage)) if voltage is not None else None,
        'amperage_rating': Decimal(str(amperage)) if amperage is not None else None,
        'phase_designation': '3P',
        'pole_designation': '3W',
        'connector_type': connector,
        'is_protected': role in (TerminalRoleChoices.ROLE_BRANCH, TerminalRoleChoices.ROLE_LOAD),
        'is_switchable': False,
        'is_monitored': False,
        'position_index': index,
        'description': short_description(f'{SOURCE_MARKER}; generated terminal.'),
    }
    counters['electrical_terminal_created' if created else 'electrical_terminal_seen'] += 1
    return save_changed(obj, desired, counters, 'electrical_terminal')


def upsert_segment(power_system, *, name, from_terminal, to_terminal, kind, domain=None, voltage=None, breaker=None, ampacity=None, counters):
    slug = stable_slug('segment', name)
    obj, created = ElectricalSegment.objects.get_or_create(
        slug=slug,
        defaults={
            'name': name[:100],
            'power_system': power_system,
            'from_terminal': from_terminal,
            'to_terminal': to_terminal,
        },
    )
    desired = {
        'name': name[:100],
        'slug': slug,
        'power_system': power_system,
        'from_terminal': from_terminal,
        'to_terminal': to_terminal,
        'segment_kind': kind,
        'path_state': TopologyStateChoices.STATE_PLANNED,
        'breaker_size_a': Decimal(str(breaker)) if breaker is not None else None,
        'voltage_nominal': Decimal(str(voltage)) if voltage is not None else None,
        'ampacity_a': Decimal(str(ampacity)) if ampacity is not None else None,
        'power_domain': domain,
        'description': short_description(f'{SOURCE_MARKER}; drawing-derived segment.'),
    }
    counters['electrical_segment_created' if created else 'electrical_segment_seen'] += 1
    return save_changed(obj, desired, counters, 'electrical_segment')


def terminal_pair(node, *, input_name='line', output_name='load', input_v=None, output_v=None, input_a=None, output_a=None, counters):
    line = upsert_terminal(
        node,
        name=input_name,
        role=TerminalRoleChoices.ROLE_LINE,
        direction=TerminalDirectionChoices.DIRECTION_SINK,
        voltage=input_v,
        amperage=input_a,
        index=1,
        counters=counters,
    )
    load = upsert_terminal(
        node,
        name=output_name,
        role=TerminalRoleChoices.ROLE_LOAD,
        direction=TerminalDirectionChoices.DIRECTION_SOURCE,
        voltage=output_v,
        amperage=output_a,
        index=2,
        counters=counters,
    )
    return line, load


def build_plant_backbone(power_system, site, counters):
    domains = {}
    for group in (1, 2):
        for priority, letter in enumerate(LETTERS, start=1):
            code = f'{group}{letter}'
            domains[code] = upsert_domain(
                power_system,
                code,
                f'Data Hall {group} IT system {letter}',
                PowerDomainKindChoices.KIND_PRIMARY,
                group * 100 + priority,
                counters,
            )
    for priority, letter in enumerate(LETTERS, start=1):
        code = f'3{letter}'
        domains[code] = upsert_domain(
            power_system,
            code,
            f'Mechanical/facility system {letter}',
            PowerDomainKindChoices.KIND_PRIMARY,
            300 + priority,
            counters,
        )

    redundancy_group = upsert_redundancy_group(
        power_system,
        [domains[f'{group}{letter}'] for group in (1, 2) for letter in LETTERS],
        counters,
    )

    utility = upsert_node(
        power_system,
        site,
        name='Duke Energy switchyard / existing 56 MVA utility transformer',
        kind=NodeKindChoices.KIND_UTILITY_SERVICE,
        role='Utility service transformer',
        model='56 MVA, 24.94/14.4 kV, 3P4W',
        output_v=24940,
        capacity_kw=56000,
        counters=counters,
    )
    utility_out_1 = upsert_terminal(
        utility,
        name='utility-breaker-1-source',
        role=TerminalRoleChoices.ROLE_OUTPUT,
        direction=TerminalDirectionChoices.DIRECTION_SOURCE,
        voltage=24940,
        amperage=636,
        index=1,
        counters=counters,
    )
    utility_out_2 = upsert_terminal(
        utility,
        name='utility-breaker-2-source',
        role=TerminalRoleChoices.ROLE_OUTPUT,
        direction=TerminalDirectionChoices.DIRECTION_SOURCE,
        voltage=24940,
        amperage=639,
        index=2,
        counters=counters,
    )

    breaker_outputs = {}
    for idx, source_terminal in ((1, utility_out_1), (2, utility_out_2)):
        breaker = upsert_node(
            power_system,
            site,
            name=f'Utility breaker {idx}',
            kind=NodeKindChoices.KIND_MV_SWITCHGEAR,
            role='Utility service breaker',
            input_v=24940,
            output_v=24940,
            counters=counters,
        )
        line, load = terminal_pair(breaker, input_v=24940, output_v=24940, input_a=650, output_a=650, counters=counters)
        upsert_segment(
            power_system,
            name=f'Utility transformer to utility breaker {idx}',
            from_terminal=source_terminal,
            to_terminal=line,
            kind=SegmentKindChoices.KIND_FEEDER,
            voltage=24940,
            ampacity=650,
            counters=counters,
        )
        breaker_outputs[idx] = load

    prsg_loads = {}
    for idx in (1, 2):
        prsg = upsert_node(
            power_system,
            site,
            name=f'PRSG-{idx}',
            kind=NodeKindChoices.KIND_MV_SWITCHGEAR,
            role='Primary switchgear lineup',
            model='1200 A, 27 kV, 31.5 kAIC',
            input_v=24940,
            output_v=24940,
            counters=counters,
        )
        line, load = terminal_pair(prsg, input_v=24940, output_v=24940, input_a=1200, output_a=1200, counters=counters)
        upsert_segment(
            power_system,
            name=f'Utility breaker {idx} to PRSG-{idx}',
            from_terminal=breaker_outputs[idx],
            to_terminal=line,
            kind=SegmentKindChoices.KIND_FEEDER,
            voltage=24940,
            ampacity=1200,
            counters=counters,
        )
        prsg_loads[idx] = load

    feeder_loads = {}
    for prsg_idx in (1, 2):
        for feeder_idx in range(1, 5):
            feeder_name = f'PRSG-{prsg_idx}-{feeder_idx}'
            feeder = upsert_node(
                power_system,
                site,
                name=feeder_name,
                kind=NodeKindChoices.KIND_MV_SWITCHGEAR,
                role='Primary switchgear feeder section',
                model='600 A, 27 kV, 31.5 kAIC',
                input_v=24940,
                output_v=24940,
                counters=counters,
            )
            line, load = terminal_pair(feeder, input_v=24940, output_v=24940, input_a=600, output_a=600, counters=counters)
            upsert_segment(
                power_system,
                name=f'PRSG-{prsg_idx} to {feeder_name}',
                from_terminal=prsg_loads[prsg_idx],
                to_terminal=line,
                kind=SegmentKindChoices.KIND_FEEDER,
                voltage=24940,
                ampacity=600,
                counters=counters,
            )
            feeder_loads[feeder_name] = load

    rpp_branch_terminals = {}
    for group in (1, 2, 3):
        for letter in LETTERS:
            system = f'{group}{letter}'
            domain = domains[system]
            transformer = upsert_node(
                power_system,
                site,
                name=f'T-{system}',
                kind=NodeKindChoices.KIND_TRANSFORMER,
                role='MV/LV transformer',
                model='3000 kVA, 24.94 kV to 480/277 V, 3P4W',
                input_v=24940,
                output_v=480,
                capacity_kw=3000,
                counters=counters,
            )
            t_line, t_load = terminal_pair(transformer, input_v=24940, output_v=480, input_a=600, output_a=4000, counters=counters)
            upsert_segment(
                power_system,
                name=f'{PRSG_FEEDER_BY_SYSTEM[system]} to T-{system}',
                from_terminal=feeder_loads[PRSG_FEEDER_BY_SYSTEM[system]],
                to_terminal=t_line,
                kind=SegmentKindChoices.KIND_FEEDER,
                domain=domain,
                voltage=24940,
                ampacity=600,
                counters=counters,
            )

            generator = upsert_node(
                power_system,
                site,
                name=f'G-{system}',
                kind=NodeKindChoices.KIND_GENERATOR,
                role='Standby generator',
                model='3000 kW, 480/277 V, 3P4W',
                output_v=480,
                capacity_kw=3000,
                counters=counters,
            )
            g_load = upsert_terminal(
                generator,
                name='generator-output',
                role=TerminalRoleChoices.ROLE_OUTPUT,
                direction=TerminalDirectionChoices.DIRECTION_SOURCE,
                voltage=480,
                amperage=4000,
                index=1,
                counters=counters,
            )

            ats = upsert_node(
                power_system,
                site,
                name=f'ATS-{system}',
                kind=NodeKindChoices.KIND_ATS,
                role='Main automatic transfer switch',
                model='4000 A, 480 V, 100 kAIC',
                input_v=480,
                output_v=480,
                counters=counters,
            )
            ats_normal = upsert_terminal(
                ats,
                name='normal-source',
                role=TerminalRoleChoices.ROLE_LINE,
                direction=TerminalDirectionChoices.DIRECTION_SINK,
                voltage=480,
                amperage=4000,
                index=1,
                counters=counters,
            )
            ats_emergency = upsert_terminal(
                ats,
                name='emergency-source',
                role=TerminalRoleChoices.ROLE_LINE,
                direction=TerminalDirectionChoices.DIRECTION_SINK,
                voltage=480,
                amperage=4000,
                index=2,
                counters=counters,
            )
            ats_load = upsert_terminal(
                ats,
                name='load',
                role=TerminalRoleChoices.ROLE_LOAD,
                direction=TerminalDirectionChoices.DIRECTION_SOURCE,
                voltage=480,
                amperage=4000,
                index=3,
                counters=counters,
            )
            upsert_segment(
                power_system,
                name=f'T-{system} to ATS-{system} normal',
                from_terminal=t_load,
                to_terminal=ats_normal,
                kind=SegmentKindChoices.KIND_FEEDER,
                domain=domain,
                voltage=480,
                ampacity=4000,
                counters=counters,
            )
            upsert_segment(
                power_system,
                name=f'G-{system} to ATS-{system} emergency',
                from_terminal=g_load,
                to_terminal=ats_emergency,
                kind=SegmentKindChoices.KIND_FEEDER,
                domain=domain,
                voltage=480,
                ampacity=4000,
                counters=counters,
            )

            mdp = upsert_node(
                power_system,
                site,
                name=f'MDP-{system}',
                kind=NodeKindChoices.KIND_LV_SWITCHBOARD,
                role='Main distribution board',
                model='4000 A, 480 V, 100 kAIC',
                input_v=480,
                output_v=480,
                counters=counters,
            )
            mdp_line, mdp_load = terminal_pair(mdp, input_v=480, output_v=480, input_a=4000, output_a=4000, counters=counters)
            upsert_segment(
                power_system,
                name=f'ATS-{system} to MDP-{system}',
                from_terminal=ats_load,
                to_terminal=mdp_line,
                kind=SegmentKindChoices.KIND_FEEDER,
                domain=domain,
                voltage=480,
                ampacity=4000,
                counters=counters,
            )

            ups_count = 3 if group in (1, 2) else 1
            for ups_idx in range(1, ups_count + 1):
                ups = upsert_node(
                    power_system,
                    site,
                    name=f'UPS-{system}-{ups_idx}',
                    kind=NodeKindChoices.KIND_UPS,
                    role='UPS module',
                    model='1100 kW, 480 V, 3P3W',
                    input_v=480,
                    output_v=480,
                    capacity_kw=1100,
                    counters=counters,
                )
                ups_line, ups_load = terminal_pair(ups, input_v=480, output_v=480, input_a=1600, output_a=1600, counters=counters)
                upsert_segment(
                    power_system,
                    name=f'MDP-{system} to UPS-{system}-{ups_idx}',
                    from_terminal=mdp_load,
                    to_terminal=ups_line,
                    kind=SegmentKindChoices.KIND_FEEDER,
                    domain=domain,
                    voltage=480,
                    ampacity=1600,
                    counters=counters,
                )

                uop = upsert_node(
                    power_system,
                    site,
                    name=f'UOP-{system}-{ups_idx}',
                    kind=NodeKindChoices.KIND_LV_SWITCHBOARD,
                    role='UPS output switchboard',
                    model='1600 A, 480 V, 100 kAIC',
                    input_v=480,
                    output_v=480,
                    counters=counters,
                )
                uop_line, uop_load = terminal_pair(uop, input_v=480, output_v=480, input_a=1600, output_a=1600, counters=counters)
                upsert_segment(
                    power_system,
                    name=f'UPS-{system}-{ups_idx} to UOP-{system}-{ups_idx}',
                    from_terminal=ups_load,
                    to_terminal=uop_line,
                    kind=SegmentKindChoices.KIND_FEEDER,
                    domain=domain,
                    voltage=480,
                    ampacity=1600,
                    counters=counters,
                )

                if group not in (1, 2):
                    continue

                for pdu_idx in (1, 2):
                    pdu = upsert_node(
                        power_system,
                        site,
                        name=f'PDU-{system}-{ups_idx}-{pdu_idx}',
                        kind=NodeKindChoices.KIND_PDU,
                        role='PDU transformer',
                        model='480 V to 415/240 V, 3P4W; 600 kVA default, 500 kVA exceptions TBD',
                        input_v=480,
                        output_v=415,
                        capacity_kw=600,
                        counters=counters,
                    )
                    pdu_line, pdu_load = terminal_pair(pdu, input_v=480, output_v=415, input_a=800, output_a=800, counters=counters)
                    upsert_segment(
                        power_system,
                        name=f'UOP-{system}-{ups_idx} to PDU-{system}-{ups_idx}-{pdu_idx}',
                        from_terminal=uop_load,
                        to_terminal=pdu_line,
                        kind=SegmentKindChoices.KIND_FEEDER,
                        domain=domain,
                        voltage=480,
                        ampacity=800,
                        counters=counters,
                    )

                    for rpp_side in (1, 2):
                        rpp_name = f'RPP-{system}-{ups_idx}-{pdu_idx}-{rpp_side}'
                        rpp = upsert_node(
                            power_system,
                            site,
                            name=rpp_name,
                            kind=NodeKindChoices.KIND_RPP,
                            role='Remote power panel',
                            model='400 A MCB, 415/240 V, 3P4W, 65 kAIC',
                            input_v=415,
                            output_v=415,
                            counters=counters,
                        )
                        rpp_line, rpp_load = terminal_pair(rpp, input_v=415, output_v=415, input_a=400, output_a=400, counters=counters)
                        upsert_segment(
                            power_system,
                            name=f'PDU-{system}-{ups_idx}-{pdu_idx} to {rpp_name}',
                            from_terminal=pdu_load,
                            to_terminal=rpp_line,
                            kind=SegmentKindChoices.KIND_FEEDER,
                            domain=domain,
                            voltage=415,
                            ampacity=400,
                            counters=counters,
                        )
                        rpp_branch_terminals[rpp_name] = rpp_load

    return domains, redundancy_group, rpp_branch_terminals


def read_circuit_rows():
    with CABINET_CIRCUIT_CSV.open(newline='') as handle:
        return list(csv.DictReader(handle))


def upsert_cabinet_circuits(power_system, site, domains, redundancy_group, rpp_branch_terminals, counters):
    unmatched_racks = set()
    exact_rack_name_matches = 0
    rows = read_circuit_rows()

    for row in rows:
        circuit_node_name = row['circuit_node']
        source_rpp = row['source_rpp']
        domain_code = row['data_hall'].split()[-1] + row['source_system']
        domain = domains.get(domain_code)
        source_terminal = rpp_branch_terminals.get(source_rpp)
        if source_terminal is None:
            counters['cabinet_circuit_missing_source_rpp'] += 1
            continue

        circuit_node = upsert_node(
            power_system,
            site,
            name=circuit_node_name,
            kind=NodeKindChoices.KIND_RACK_CIRCUIT_TERMINATOR,
            role=f"{row['equipment_type']} cabinet circuit",
            model=f"rack_id={row['rack_id']}; circuit={row['circuit']}",
            input_v=415,
            output_v=415,
            capacity_kw=Decimal(row['maximum_kva']),
            counters=counters,
        )
        circuit_in = upsert_terminal(
            circuit_node,
            name='rpp-branch-input',
            role=TerminalRoleChoices.ROLE_INPUT,
            direction=TerminalDirectionChoices.DIRECTION_SINK,
            voltage=415,
            amperage=Decimal(row['ocpd_a']),
            index=int(row['circuit']),
            counters=counters,
        )
        upsert_segment(
            power_system,
            name=f"{source_rpp} to {circuit_node_name}",
            from_terminal=source_terminal,
            to_terminal=circuit_in,
            kind=SegmentKindChoices.KIND_BRANCH_CIRCUIT,
            domain=domain,
            voltage=415,
            breaker=Decimal(row['ocpd_a']),
            ampacity=Decimal(row['ocpd_a']),
            counters=counters,
        )

        rack = Rack.objects.filter(site=site, name=row['rack_id']).first()
        if rack is None:
            unmatched_racks.add(row['rack_id'])
            continue

        exact_rack_name_matches += 1

    counters['cabinet_circuit_rows_seen'] = len(rows)
    counters['cabinet_circuit_unique_racks_seen'] = len({row['rack_id'] for row in rows})
    counters['cabinet_circuit_unmatched_racks'] = len(unmatched_racks)
    counters['cabinet_circuit_exact_rack_name_matches'] = exact_rack_name_matches
    return sorted(unmatched_racks)


def power_ports_for_rack(rack, *, device_type_slugs, port_names):
    return list(
        PowerPort.objects.select_related('device', 'device__device_type', 'device__rack')
        .filter(
            device__site__slug=MAD_SITE_SLUG,
            device__rack=rack,
            device__device_type__slug__in=device_type_slugs,
            name__in=port_names,
        )
        .order_by('device__position', 'device__name', 'name')
    )


def upsert_bus(power_system, rack, counters):
    name = f'NVL72 Busbar {rack.name}'
    bus, created = InternalPowerBus.objects.get_or_create(
        rack=rack,
        name=name,
        defaults={
            'slug': stable_slug('internal-power-bus', rack.name),
            'power_system': power_system,
        },
    )
    desired = {
        'name': name,
        'slug': stable_slug('internal-power-bus', rack.name),
        'power_system': power_system,
        'rack': rack,
        'bus_role': InternalPowerBusRoleChoices.ROLE_BUSBAR,
        'supply_type': SupplyTypeChoices.SUPPLY_DC,
        'nominal_voltage': Decimal('50.00'),
        'design_state': DesignStateChoices.STATE_PLANNED,
        'description': short_description(f'{SOURCE_MARKER}; NVL72 rack-internal shared DC busbar.'),
    }
    counters['internal_power_bus_created' if created else 'internal_power_bus_seen'] += 1
    return save_changed(bus, desired, counters, 'internal_power_bus')


def upsert_bus_attachment(bus, power_port, role, position_index, counters):
    name = f'{bus.rack.name} {role} {power_port.device.name} {power_port.name}'[:100]
    obj, created = InternalPowerBusAttachment.objects.get_or_create(
        internal_power_bus=bus,
        power_port=power_port,
        defaults={
            'name': name,
            'slug': stable_slug('bus-attachment', bus.rack.name, power_port.device.name, power_port.name),
            'attachment_role': role,
        },
    )
    desired = {
        'name': name,
        'slug': stable_slug('bus-attachment', bus.rack.name, power_port.device.name, power_port.name),
        'internal_power_bus': bus,
        'power_port': power_port,
        'attachment_role': role,
        'position_index': position_index,
        'design_state': DesignStateChoices.STATE_PLANNED,
        'description': short_description(f'{SOURCE_MARKER}; native PowerPort attached to plugin busbar.'),
    }
    counters['internal_power_bus_attachment_created' if created else 'internal_power_bus_attachment_seen'] += 1
    return save_changed(obj, desired, counters, 'internal_power_bus_attachment')


def upsert_nvl72_internal_buses(power_system, counters):
    racks = Rack.objects.filter(site__slug=MAD_SITE_SLUG, role__slug=NVL72_RACK_ROLE_SLUG).order_by('name')
    complete = []
    incomplete = []
    for rack in racks:
        source_ports = power_ports_for_rack(
            rack,
            device_type_slugs=POWER_SHELF_DEVICE_TYPE_SLUGS,
            port_names=(POWER_SHELF_PORT_NAME,),
        )
        load_ports = power_ports_for_rack(
            rack,
            device_type_slugs=LOAD_DEVICE_TYPE_SLUGS,
            port_names=LOAD_POWER_PORT_NAMES,
        )
        if not source_ports and not load_ports:
            counters['nvl72_bus_rack_no_power_ports'] += 1
            continue

        bus = upsert_bus(power_system, rack, counters)
        for index, port in enumerate(source_ports, start=1):
            upsert_bus_attachment(bus, port, InternalPowerBusAttachmentRoleChoices.ROLE_SOURCE, index, counters)
        for index, port in enumerate(load_ports, start=1):
            upsert_bus_attachment(bus, port, InternalPowerBusAttachmentRoleChoices.ROLE_LOAD, index, counters)

        if len(source_ports) == 8 and len(load_ports) == 29:
            complete.append(rack.name)
        else:
            incomplete.append((rack.name, len(source_ports), len(load_ports)))

    counters['nvl72_bus_complete_racks'] = len(complete)
    counters['nvl72_bus_incomplete_racks'] = len(incomplete)
    counters['nvl72_racks_seen'] = racks.count()
    return incomplete


def main():
    counters = Counter()
    site = Site.objects.get(slug=MAD_SITE_SLUG)

    with transaction.atomic():
        power_system = upsert_power_system(site, counters)
        domains, redundancy_group, rpp_branch_terminals = build_plant_backbone(power_system, site, counters)
        unmatched_racks = upsert_cabinet_circuits(
            power_system,
            site,
            domains,
            redundancy_group,
            rpp_branch_terminals,
            counters,
        )
        incomplete_nvl72_buses = upsert_nvl72_internal_buses(power_system, counters)

    print('Madison power-plant initial pass complete.')
    for key in sorted(counters):
        print(f'{key}={counters[key]}')
    if unmatched_racks:
        print('unmatched_electrical_rack_ids_sample=' + ','.join(unmatched_racks[:20]))
    if incomplete_nvl72_buses:
        sample = ';'.join(f'{name}:sources={sources}:loads={loads}' for name, sources, loads in incomplete_nvl72_buses[:20])
        print('incomplete_nvl72_bus_sample=' + sample)

    print('final_counts:')
    for cls in (
        PowerSystem,
        PowerDomain,
        RedundancyGroup,
        ElectricalNode,
        ElectricalTerminal,
        ElectricalSegment,
        PowerHandoffPoint,
        InternalPowerBus,
        InternalPowerBusAttachment,
    ):
        print(f'{cls.__name__}={cls.objects.count()}')


try:
    main()
except ValidationError as exc:
    print('ValidationError while seeding Madison power plant:')
    print(exc)
    raise
