# Generated by Django 5.2.12 on 2026-04-18 16:20

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_plant_graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scope_label', models.CharField(blank=True, max_length=200)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('job', 'Job'), ('post_rebuild', 'Post Rebuild')], default='manual', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_runs', to='netbox_plant_graph.fabric')),
                ('scope_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='netbox_plant_graph.fabric'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='first_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_findings', to='netbox_plant_graph.auditrun'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='last_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_findings', to='netbox_plant_graph.auditrun'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='plane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='netbox_plant_graph.fabricplane'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=32),
        ),
    ]
