# Generated by Django 5.2.12 on 2026-04-18 17:40

from django.conf import settings
import django.db.models.deletion

import taggit.managers
import utilities.json
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netbox_plant_graph', '0003_auditfinding_workflow_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='netbox_plant_graph.auditfinding')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-created', '-pk'),
            },
            bases=(models.Model,),
        ),
        migrations.AlterField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditfindingevent',
            name='event_type',
            field=models.CharField(choices=[('opened', 'Opened'), ('reopened', 'Reopened'), ('status_changed', 'Status Changed'), ('suppressed', 'Suppressed'), ('unsuppressed', 'Unsuppressed'), ('expired', 'Expired'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto Resolved')], max_length=50),
        ),
    ]
