# Generated by Django 5.2.12 on 2026-04-19 00:00

from django.conf import settings
import django.db.models.deletion

import taggit.managers
import utilities.json
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netbox_plant_graph', '0004_auditsuppression_and_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisjointnessException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('policy_mode', models.CharField(blank=True, choices=[('full', 'Full'), ('tier_aware', 'Tier Aware'), ('best_effort', 'Best Effort')], max_length=50)),
                ('exception_type', models.CharField(choices=[('shared_passive_artifact', 'Shared Passive Artifact'), ('cross_plane_fine_edge', 'Cross-Plane Fine Edge'), ('contamination_domain', 'Contamination Domain')], default='shared_passive_artifact', max_length=64)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scope_kind', models.CharField(choices=[('artifact', 'Artifact'), ('edge', 'Edge'), ('domain', 'Domain'), ('path_pair', 'Path Pair'), ('lane_group', 'Lane Group')], default='artifact', max_length=32)),
                ('lane_selector', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('expired', 'Expired')], db_index=True, default='draft', max_length=32)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disjointness_exceptions', to='netbox_plant_graph.fabric')),
                ('plane_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_plant_graph.fabricplane')),
                ('plane_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_plant_graph.fabricplane')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('fabric', '-created', '-pk'),
            },
            bases=(models.Model,),
        ),
    ]
