# Generated by Django 5.2.12 on 2026-04-19 00:00

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_plant_graph', '0005_disjointnessexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphBuildRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scope_label', models.CharField(blank=True, max_length=200)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('job', 'Job'), ('incremental', 'Incremental'), ('post_change', 'Post Change')], default='manual', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_build_runs', to='netbox_plant_graph.fabric')),
                ('scope_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
                'indexes': [
                    models.Index(fields=['fabric', 'status', 'started_at'], name='netbox_plan_fabric__1341df_idx'),
                    models.Index(fields=['fabric', 'completed_at'], name='netbox_plan_fabric__731d81_idx'),
                    models.Index(fields=['trigger_mode', 'started_at'], name='netbox_plan_trigger_c2d4d0_idx'),
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
