# Generated by Django 5.2.12 on 2026-04-20 00:13

import django.db.models.deletion

import taggit.managers
import utilities.json
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0122_charfield_null_choices'),
        ('netbox_plant_graph', '0006_graphbuildrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedStateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scope_label', models.CharField(blank=True, max_length=200)),
                ('summary_kind', models.CharField(choices=[('lane_group', 'Lane Group'), ('segment', 'Segment')], default='lane_group', max_length=32)),
                ('cause_code', models.CharField(choices=[('missing_cable_profile', 'Missing Cable Profile'), ('missing_child_interface', 'Missing Child Interface'), ('incomplete_child_interface_set', 'Incomplete Child Interface Set'), ('missing_port_mapping', 'Missing Port Mapping'), ('profile_returned_none', 'Profile Returned None'), ('profile_error', 'Profile Error'), ('missing_peer_position', 'Missing Peer Position'), ('orphaned_attachment_unit', 'Orphaned Attachment Unit')], default='missing_cable_profile', max_length=64)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('representative_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('plane_ids', models.JSONField(blank=True, default=list)),
                ('selector', models.JSONField(blank=True, default=dict)),
                ('anchors', models.JSONField(blank=True, default=dict)),
                ('impact', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_state_summaries', to='netbox_plant_graph.fabric')),
                ('first_seen_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_unresolved_summaries', to='netbox_plant_graph.graphbuildrun')),
                ('last_seen_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_unresolved_summaries', to='netbox_plant_graph.graphbuildrun')),
                ('owner_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('plane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unresolved_state_summaries', to='netbox_plant_graph.fabricplane')),
                ('representative_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('scope_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('cause_code', '-last_seen_at', '-pk'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UnresolvedStateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('observed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('impact', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unresolved_state_observations', to='netbox_plant_graph.graphbuildrun')),
                ('related_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unresolved_state_observations', to='netbox_plant_graph.auditrun')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='netbox_plant_graph.unresolvedstatesummary')),
            ],
            options={
                'ordering': ('-observed_at', '-pk'),
            },
            bases=(models.Model,),
        ),
        migrations.AddIndex(
            model_name='unresolvedstatesummary',
            index=models.Index(fields=['fabric', 'active', 'last_seen_at'], name='netbox_plan_fabric__dcaf79_idx'),
        ),
        migrations.AddIndex(
            model_name='unresolvedstatesummary',
            index=models.Index(fields=['fabric', 'cause_code', 'active'], name='netbox_plan_fabric__2af420_idx'),
        ),
        migrations.AddIndex(
            model_name='unresolvedstatesummary',
            index=models.Index(fields=['owner_object_type', 'owner_object_id', 'active'], name='netbox_plan_owner_o_99ff89_idx'),
        ),
        migrations.AddIndex(
            model_name='unresolvedstatesummary',
            index=models.Index(fields=['representative_object_type', 'representative_object_id'], name='netbox_plan_represe_f895e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='unresolvedstatesummary',
            constraint=models.UniqueConstraint(fields=('fabric', 'scope_type', 'scope_id', 'fingerprint'), name='netbox_plant_graph_unresolved_summary_scope_fingerprint_uniq'),
        ),
        migrations.AddIndex(
            model_name='unresolvedstateobservation',
            index=models.Index(fields=['build', 'observed_at'], name='netbox_plan_build_i_3d407a_idx'),
        ),
        migrations.AddIndex(
            model_name='unresolvedstateobservation',
            index=models.Index(fields=['summary', 'observed_at'], name='netbox_plan_summary_8e1488_idx'),
        ),
        migrations.AddConstraint(
            model_name='unresolvedstateobservation',
            constraint=models.UniqueConstraint(fields=('summary', 'build'), name='netbox_plant_graph_unresolved_observation_summary_build_uniq'),
        ),
    ]
