# Generated by Django 5.2.12 on 2026-04-20 04:00

import django.db.models.deletion

import taggit.managers
import utilities.json
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('netbox_plant_graph', '0007_unresolvedstatesummary_unresolvedstateobservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('assembly_type', models.CharField(default='shuffle_trunk', max_length=50)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('cable_profile_hint', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.devicetype')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AssemblyConnectorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('side', models.CharField(max_length=1)),
                ('connector_number', models.PositiveIntegerField()),
                ('connector_type', models.CharField(default='mpo-12', max_length=50)),
                ('position_count', models.PositiveIntegerField(default=8)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='netbox_plant_graph.assemblytemplate')),
            ],
            options={
                'ordering': ('template', 'side', 'connector_number'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AssemblyMappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('a_position', models.PositiveSmallIntegerField()),
                ('b_position', models.PositiveSmallIntegerField()),
                ('mapping_type', models.CharField(default='identity', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('a_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_mappings', to='netbox_plant_graph.assemblyconnectortemplate')),
                ('b_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_mappings', to='netbox_plant_graph.assemblyconnectortemplate')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='netbox_plant_graph.assemblytemplate')),
            ],
            options={
                'ordering': ('template', 'a_connector', 'a_position'),
                'constraints': [models.UniqueConstraint(fields=('template', 'a_connector', 'a_position'), name='netbox_plant_graph_assembly_mapping_a_position_uniq'), models.UniqueConstraint(fields=('template', 'b_connector', 'b_position'), name='netbox_plant_graph_assembly_mapping_b_position_uniq')],
            },
            bases=(models.Model,),
        ),
        migrations.AddConstraint(
            model_name='assemblyconnectortemplate',
            constraint=models.UniqueConstraint(fields=('template', 'side', 'connector_number'), name='netbox_plant_graph_assembly_connector_side_number_uniq'),
        ),
    ]
