# Generated by Django 5.2.12 on 2026-04-20 04:16

import django.db.models.deletion

import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('netbox_plant_graph', '0008_assembly_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_plans', to='netbox_plant_graph.fabric')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-created', '-pk'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RackPopulationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rack_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.racktype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SpatialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('root_node_type', models.CharField(default='building', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SpatialTemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name_pattern', models.CharField(max_length=200)),
                ('node_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('position_x', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('position_y', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('position_z', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('position_x_stride', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('position_y_stride', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='netbox_plant_graph.spatialtemplatenode')),
                ('rack_population_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_plant_graph.rackpopulationtemplate')),
                ('rack_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.racktype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='netbox_plant_graph.spatialtemplate')),
            ],
            options={
                'ordering': ('template', 'sort_order', 'pk'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StampRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('template_id', models.PositiveBigIntegerField()),
                ('result_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('stamped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('error_detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stamp_records', to='netbox_plant_graph.deploymentplan')),
                ('result_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('stamped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('plan', 'pk'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RackPopulationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('u_position', models.DecimalField(decimal_places=1, max_digits=4)),
                ('face', models.CharField(default='front', max_length=10)),
                ('name_pattern', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assembly_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_plant_graph.assemblytemplate')),
                ('device_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.devicerole')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='netbox_plant_graph.rackpopulationtemplate')),
            ],
            options={
                'ordering': ('template', 'u_position', 'face'),
                'constraints': [models.UniqueConstraint(fields=('template', 'u_position', 'face'), name='netbox_plant_graph_rack_pop_slot_position_face_uniq')],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SpatialPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('target_id', models.PositiveBigIntegerField()),
                ('reference_frame_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('position_x', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('position_z', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('orientation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('coordinate_unit', models.CharField(default='meters', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reference_frame_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('target_type', 'target_id'),
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_id'), name='netbox_plant_graph_spatial_placement_target_uniq')],
            },
            bases=(models.Model,),
        ),
    ]
