# Generated by Django 5.2.12 on 2026-04-21 23:28

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_plant_graph', '0011_batch_schema_additions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devicechildinterfacespec',
            name='netbox_plant_graph_devicechildinterfacespec_bt_parent_uniq',
        ),
        migrations.AddField(
            model_name='breakoutprofile',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='devicebreakouttemplate',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='devicechildinterfacespec',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='breakoutprofile',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='devicebreakouttemplate',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='devicechildinterfacespec',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterUniqueTogether(
            name='devicechildinterfacespec',
            unique_together={('breakout_template', 'parent_interface_name')},
        ),
    ]
