# Generated by Django 5.2.12 on 2026-04-21 23:34

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_plant_graph', '0012_remove_devicechildinterfacespec_netbox_plant_graph_devicechildinterfacespec_bt_parent_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackpopulationtemplate',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_plant_graph.fabric'),
        ),
        migrations.AddField(
            model_name='rackpopulationtemplate',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rackpopulationtemplate',
            name='plane_multiplier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spatialtemplate',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spatialtemplatenode',
            name='quantity_expr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ConnectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('source_slot_index', models.PositiveIntegerField()),
                ('source_connector_number', models.PositiveIntegerField(default=1)),
                ('dest_slot_index', models.PositiveIntegerField()),
                ('dest_connector_number', models.PositiveIntegerField(default=1)),
                ('enumeration_mode', models.CharField(default='one_to_one', max_length=20)),
                ('label_pattern', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assembly_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_plant_graph.assemblytemplate')),
                ('dest_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_connections', to='netbox_plant_graph.spatialtemplatenode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='netbox_plant_graph.spatialtemplatenode')),
                ('spatial_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='netbox_plant_graph.spatialtemplate')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('spatial_template', 'sort_order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('spatial_template', 'name'), name='netbox_plant_graph_connection_template_name_uniq')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
