from dataclasses import dataclass


@dataclass(frozen=True)
class DetailFieldSpec:
    name: str
    label: str


DETAIL_SPECS = {
    'fabric': (
        DetailFieldSpec(name='name', label='Name'),
        DetailFieldSpec(name='description', label='Description'),
        DetailFieldSpec(name='expected_plane_count', label='Expected Plane Count'),
        DetailFieldSpec(name='tier_depth', label='Tier Depth'),
        DetailFieldSpec(name='disjointness_policy', label='Disjointness Policy'),
    ),
    'fabricplane': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='plane_number', label='Plane Number'),
        DetailFieldSpec(name='description', label='Description'),
    ),
    'plantnode': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='name', label='Name'),
        DetailFieldSpec(name='node_type', label='Node Type'),
        DetailFieldSpec(name='role', label='Role'),
        DetailFieldSpec(name='status', label='Status'),
    ),
    'auditrun': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='scope_label', label='Scope'),
        DetailFieldSpec(name='trigger_mode', label='Trigger Mode'),
        DetailFieldSpec(name='status', label='Status'),
        DetailFieldSpec(name='started_at', label='Started'),
        DetailFieldSpec(name='completed_at', label='Completed'),
        DetailFieldSpec(name='finding_count', label='Findings'),
        DetailFieldSpec(name='new_count', label='New'),
        DetailFieldSpec(name='reopened_count', label='Reopened'),
        DetailFieldSpec(name='resolved_count', label='Resolved'),
    ),
    'graphbuildrun': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='scope_label', label='Scope'),
        DetailFieldSpec(name='trigger_mode', label='Trigger Mode'),
        DetailFieldSpec(name='status', label='Status'),
        DetailFieldSpec(name='started_at', label='Started'),
        DetailFieldSpec(name='completed_at', label='Completed'),
        DetailFieldSpec(name='stats', label='Stats'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'unresolvedstatesummary': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='plane', label='Plane'),
        DetailFieldSpec(name='scope_label', label='Scope'),
        DetailFieldSpec(name='summary_kind', label='Summary Kind'),
        DetailFieldSpec(name='cause_code', label='Cause Code'),
        DetailFieldSpec(name='fingerprint', label='Fingerprint'),
        DetailFieldSpec(name='active', label='Active'),
        DetailFieldSpec(name='owner_object', label='Owner Object'),
        DetailFieldSpec(name='representative_object', label='Representative Object'),
        DetailFieldSpec(name='first_seen_build', label='First Seen Build'),
        DetailFieldSpec(name='last_seen_build', label='Last Seen Build'),
        DetailFieldSpec(name='first_seen_at', label='First Seen At'),
        DetailFieldSpec(name='last_seen_at', label='Last Seen At'),
        DetailFieldSpec(name='resolved_at', label='Resolved At'),
        DetailFieldSpec(name='plane_ids', label='Plane IDs'),
        DetailFieldSpec(name='selector', label='Selector'),
        DetailFieldSpec(name='anchors', label='Anchors'),
        DetailFieldSpec(name='impact', label='Impact'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'unresolvedstateobservation': (
        DetailFieldSpec(name='summary', label='Summary'),
        DetailFieldSpec(name='build', label='Build'),
        DetailFieldSpec(name='observed_at', label='Observed At'),
        DetailFieldSpec(name='impact', label='Impact'),
        DetailFieldSpec(name='related_audit_run', label='Related Audit Run'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'auditfinding': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='plane', label='Plane'),
        DetailFieldSpec(name='finding_type', label='Finding Type'),
        DetailFieldSpec(name='severity', label='Severity'),
        DetailFieldSpec(name='status', label='Status'),
        DetailFieldSpec(name='active', label='Active'),
        DetailFieldSpec(name='object', label='Affected Object'),
        DetailFieldSpec(name='assigned_to', label='Assigned To'),
        DetailFieldSpec(name='acknowledged_by', label='Acknowledged By'),
        DetailFieldSpec(name='first_seen_at', label='First Seen'),
        DetailFieldSpec(name='last_seen_at', label='Last Seen'),
        DetailFieldSpec(name='resolved_at', label='Resolved At'),
        DetailFieldSpec(name='message', label='Message'),
        DetailFieldSpec(name='resolution_summary', label='Resolution Summary'),
    ),
    'auditfindingevent': (
        DetailFieldSpec(name='finding', label='Finding'),
        DetailFieldSpec(name='run', label='Audit Run'),
        DetailFieldSpec(name='event_type', label='Event Type'),
        DetailFieldSpec(name='actor', label='Actor'),
        DetailFieldSpec(name='old_status', label='Old Status'),
        DetailFieldSpec(name='new_status', label='New Status'),
        DetailFieldSpec(name='message', label='Message'),
        DetailFieldSpec(name='created', label='Created'),
    ),
    'auditsuppression': (
        DetailFieldSpec(name='finding', label='Finding'),
        DetailFieldSpec(name='created_by', label='Created By'),
        DetailFieldSpec(name='reason', label='Reason'),
        DetailFieldSpec(name='expires_at', label='Expires At'),
        DetailFieldSpec(name='active', label='Active'),
        DetailFieldSpec(name='created', label='Created'),
    ),
    'disjointnessexception': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='policy_mode', label='Policy Mode'),
        DetailFieldSpec(name='exception_type', label='Exception Type'),
        DetailFieldSpec(name='target', label='Target'),
        DetailFieldSpec(name='plane_a', label='Plane A'),
        DetailFieldSpec(name='plane_b', label='Plane B'),
        DetailFieldSpec(name='scope_kind', label='Scope Kind'),
        DetailFieldSpec(name='reason', label='Reason'),
        DetailFieldSpec(name='approved_by', label='Approved By'),
        DetailFieldSpec(name='approved_at', label='Approved At'),
        DetailFieldSpec(name='expires_at', label='Expires At'),
        DetailFieldSpec(name='status', label='Status'),
        DetailFieldSpec(name='active', label='Active'),
    ),
    # --- Planning / Assembly Templates ---
    'assemblytemplate': (
        DetailFieldSpec(name='name', label='Name'),
        DetailFieldSpec(name='slug', label='Slug'),
        DetailFieldSpec(name='description', label='Description'),
        DetailFieldSpec(name='assembly_type', label='Assembly Type'),
        DetailFieldSpec(name='manufacturer', label='Manufacturer'),
        DetailFieldSpec(name='part_number', label='Part Number'),
        DetailFieldSpec(name='device_type', label='Device Type'),
        DetailFieldSpec(name='cable_profile_hint', label='Cable Profile Hint'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'assemblyconnectortemplate': (
        DetailFieldSpec(name='template', label='Assembly Template'),
        DetailFieldSpec(name='side', label='Side'),
        DetailFieldSpec(name='connector_number', label='Connector Number'),
        DetailFieldSpec(name='connector_type', label='Connector Type'),
        DetailFieldSpec(name='position_count', label='Position Count'),
        DetailFieldSpec(name='label', label='Label'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'assemblymappingtemplate': (
        DetailFieldSpec(name='template', label='Assembly Template'),
        DetailFieldSpec(name='a_connector', label='A Connector'),
        DetailFieldSpec(name='a_position', label='A Position'),
        DetailFieldSpec(name='b_connector', label='B Connector'),
        DetailFieldSpec(name='b_position', label='B Position'),
        DetailFieldSpec(name='mapping_type', label='Mapping Type'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    # --- Planning / Spatial Placement ---
    'spatialplacement': (
        DetailFieldSpec(name='target', label='Target'),
        DetailFieldSpec(name='reference_frame', label='Reference Frame'),
        DetailFieldSpec(name='position_x', label='X'),
        DetailFieldSpec(name='position_y', label='Y'),
        DetailFieldSpec(name='position_z', label='Z'),
        DetailFieldSpec(name='orientation', label='Orientation'),
        DetailFieldSpec(name='coordinate_unit', label='Unit'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    # --- Planning / Spatial Templates ---
    'spatialtemplate': (
        DetailFieldSpec(name='name', label='Name'),
        DetailFieldSpec(name='slug', label='Slug'),
        DetailFieldSpec(name='description', label='Description'),
        DetailFieldSpec(name='root_node_type', label='Root Node Type'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'spatialtemplatenode': (
        DetailFieldSpec(name='template', label='Spatial Template'),
        DetailFieldSpec(name='parent', label='Parent Node'),
        DetailFieldSpec(name='name_pattern', label='Name Pattern'),
        DetailFieldSpec(name='node_type', label='Node Type'),
        DetailFieldSpec(name='quantity', label='Quantity'),
        DetailFieldSpec(name='sort_order', label='Sort Order'),
        DetailFieldSpec(name='position_x', label='X'),
        DetailFieldSpec(name='position_y', label='Y'),
        DetailFieldSpec(name='position_z', label='Z'),
        DetailFieldSpec(name='position_x_stride', label='X Stride'),
        DetailFieldSpec(name='position_y_stride', label='Y Stride'),
        DetailFieldSpec(name='rack_type', label='Rack Type'),
        DetailFieldSpec(name='rack_population_template', label='Rack Population Template'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    # --- Planning / Deployment Plan & Stamp Provenance ---
    'deploymentplan': (
        DetailFieldSpec(name='fabric', label='Fabric'),
        DetailFieldSpec(name='name', label='Name'),
        DetailFieldSpec(name='description', label='Description'),
        DetailFieldSpec(name='status', label='Status'),
        DetailFieldSpec(name='created_by', label='Created By'),
        DetailFieldSpec(name='approved_by', label='Approved By'),
        DetailFieldSpec(name='approved_at', label='Approved At'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'stamprecord': (
        DetailFieldSpec(name='plan', label='Deployment Plan'),
        DetailFieldSpec(name='template', label='Template'),
        DetailFieldSpec(name='result', label='Result'),
        DetailFieldSpec(name='parameters', label='Parameters'),
        DetailFieldSpec(name='stamped_at', label='Stamped At'),
        DetailFieldSpec(name='stamped_by', label='Stamped By'),
        DetailFieldSpec(name='status', label='Status'),
        DetailFieldSpec(name='error_detail', label='Error Detail'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    # --- Planning / Rack Population Templates ---
    'rackpopulationtemplate': (
        DetailFieldSpec(name='name', label='Name'),
        DetailFieldSpec(name='slug', label='Slug'),
        DetailFieldSpec(name='description', label='Description'),
        DetailFieldSpec(name='rack_type', label='Rack Type'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
    'rackpopulationslot': (
        DetailFieldSpec(name='template', label='Rack Population Template'),
        DetailFieldSpec(name='u_position', label='U Position'),
        DetailFieldSpec(name='face', label='Face'),
        DetailFieldSpec(name='device_type', label='Device Type'),
        DetailFieldSpec(name='device_role', label='Device Role'),
        DetailFieldSpec(name='name_pattern', label='Name Pattern'),
        DetailFieldSpec(name='assembly_template', label='Assembly Template'),
        DetailFieldSpec(name='sort_order', label='Sort Order'),
        DetailFieldSpec(name='metadata', label='Metadata'),
    ),
}
