const { chromium } = require('../.tmp/playwright-run/node_modules/playwright');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1200 } });
  const dismiss = async () => { const hide = page.locator('#djHideToolBarButton'); if (await hide.count()) { try { await hide.first().click({ timeout: 1500 }); await page.waitForTimeout(250); } catch {} } };
  await page.goto('http://127.0.0.1:8000/login/?next=/', { waitUntil: 'networkidle' });
  await dismiss();
  await page.getByLabel('Username').fill('admin');
  await page.getByLabel('Password').fill('Ig49XIWlQIzmzYYSaYEGKOvc');
  await page.locator('form button[type="submit"]').first().click();
  await page.waitForLoadState('networkidle');
  await dismiss();
  await page.goto('http://127.0.0.1:8000/tenancy/tenants/add/', { waitUntil: 'networkidle' });
  await dismiss();
  await page.getByLabel('Name').fill('Operator');
  await page.getByLabel('Slug').fill('operator');
  await page.getByLabel('Description').fill('Infrastructure owner for shared resources');
  await page.screenshot({ path: 'docs/images/runbook-roce-phase1-ui/probe-before-create.png', fullPage: true });
  await page.getByRole('button', { name: /^create$/i }).click();
  await page.waitForLoadState('networkidle');
  await dismiss();
  console.log('url', page.url());
  console.log('title', await page.title());
  console.log('alerts', await page.locator('.alert').allTextContents());
  console.log('h1', await page.locator('h1').first().textContent().catch(() => 'NO_H1'));
  console.log('body-has-operator', await page.locator('body').textContent().then(t => t.includes('Operator')));
  await page.screenshot({ path: 'docs/images/runbook-roce-phase1-ui/probe-after-create.png', fullPage: true });
  await browser.close();
})();
